//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveYourTower.ConsoleUI {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class LevelsSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static LevelsSettings defaultInstance = ((LevelsSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LevelsSettings())));
        
        public static LevelsSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int IterationLatency {
            get {
                return ((int)(this["IterationLatency"]));
            }
            set {
                this["IterationLatency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int EnemyGenerationLanency {
            get {
                return ((int)(this["EnemyGenerationLanency"]));
            }
            set {
                this["EnemyGenerationLanency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int MaxLevel {
            get {
                return ((int)(this["MaxLevel"]));
            }
            set {
                this["MaxLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int Level1EnemyCount {
            get {
                return ((int)(this["Level1EnemyCount"]));
            }
            set {
                this["Level1EnemyCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int Level2EnemyCount {
            get {
                return ((int)(this["Level2EnemyCount"]));
            }
            set {
                this["Level2EnemyCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int Level3EnemyCount {
            get {
                return ((int)(this["Level3EnemyCount"]));
            }
            set {
                this["Level3EnemyCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Level1EnemyDamage {
            get {
                return ((int)(this["Level1EnemyDamage"]));
            }
            set {
                this["Level1EnemyDamage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Level2EnemyDamage {
            get {
                return ((int)(this["Level2EnemyDamage"]));
            }
            set {
                this["Level2EnemyDamage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Level3EnemyDamage {
            get {
                return ((int)(this["Level3EnemyDamage"]));
            }
            set {
                this["Level3EnemyDamage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public double Level2EnemyVelocity {
            get {
                return ((double)(this["Level2EnemyVelocity"]));
            }
            set {
                this["Level2EnemyVelocity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public double Level3EnemyVelocity {
            get {
                return ((double)(this["Level3EnemyVelocity"]));
            }
            set {
                this["Level3EnemyVelocity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Level1EnemyLife {
            get {
                return ((int)(this["Level1EnemyLife"]));
            }
            set {
                this["Level1EnemyLife"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Level2EnemyLife {
            get {
                return ((int)(this["Level2EnemyLife"]));
            }
            set {
                this["Level2EnemyLife"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Level3EnemyLife {
            get {
                return ((int)(this["Level3EnemyLife"]));
            }
            set {
                this["Level3EnemyLife"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Level1EnemyPowerRising {
            get {
                return ((int)(this["Level1EnemyPowerRising"]));
            }
            set {
                this["Level1EnemyPowerRising"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Level2EnemyPowerRising {
            get {
                return ((int)(this["Level2EnemyPowerRising"]));
            }
            set {
                this["Level2EnemyPowerRising"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Level3EnemyPowerRising {
            get {
                return ((int)(this["Level3EnemyPowerRising"]));
            }
            set {
                this["Level3EnemyPowerRising"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int TowerLife {
            get {
                return ((int)(this["TowerLife"]));
            }
            set {
                this["TowerLife"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int TowerCannonBallLifeTime {
            get {
                return ((int)(this["TowerCannonBallLifeTime"]));
            }
            set {
                this["TowerCannonBallLifeTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int TurretCannonBallLifeTime {
            get {
                return ((int)(this["TurretCannonBallLifeTime"]));
            }
            set {
                this["TurretCannonBallLifeTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int TowerCannonDamage {
            get {
                return ((int)(this["TowerCannonDamage"]));
            }
            set {
                this["TowerCannonDamage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int TurretCannonDamage {
            get {
                return ((int)(this["TurretCannonDamage"]));
            }
            set {
                this["TurretCannonDamage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int AllHitSpellDamage {
            get {
                return ((int)(this["AllHitSpellDamage"]));
            }
            set {
                this["AllHitSpellDamage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int AllSlowSpellRatio {
            get {
                return ((int)(this["AllSlowSpellRatio"]));
            }
            set {
                this["AllSlowSpellRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public int AllSlowSpellDuration {
            get {
                return ((int)(this["AllSlowSpellDuration"]));
            }
            set {
                this["AllSlowSpellDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int EnemyCollierRadius {
            get {
                return ((int)(this["EnemyCollierRadius"]));
            }
            set {
                this["EnemyCollierRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CannonBallColliderRadius {
            get {
                return ((int)(this["CannonBallColliderRadius"]));
            }
            set {
                this["CannonBallColliderRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double TowerCannonBallVelosity {
            get {
                return ((double)(this["TowerCannonBallVelosity"]));
            }
            set {
                this["TowerCannonBallVelosity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double TurretCannonBallVelosity {
            get {
                return ((double)(this["TurretCannonBallVelosity"]));
            }
            set {
                this["TurretCannonBallVelosity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int TowerColliderRadius {
            get {
                return ((int)(this["TowerColliderRadius"]));
            }
            set {
                this["TowerColliderRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int TurretColliderRadius {
            get {
                return ((int)(this["TurretColliderRadius"]));
            }
            set {
                this["TurretColliderRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double Level1EnemyVelocity {
            get {
                return ((double)(this["Level1EnemyVelocity"]));
            }
            set {
                this["Level1EnemyVelocity"] = value;
            }
        }
    }
}
